Lint/ShadowedArgument:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
