Bundler/OrderedGems:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Lint/BigDecimalNew:
  Enabled: false
Lint/ScriptPermission:
  Enabled: false
Lint/ShadowedArgument:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Lint/UnneededSplatExpansion:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/SymbolArray:
  Enabled: false
