Lint/ShadowedArgument:
  Enabled: false
Lint/UnneededSplatExpansion:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
