# For usage, see https://github.com/Safecast/safecastapi/wiki/Dev:-Setup-on-Linux
version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      DATABASE_HOST: 'postgresql'
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
    volumes:
      - .:/src
    depends_on:
      - postgresql
      - elasticsearch
      - nginx
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    environment:
      discovery.type: single-node
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - nginx-data:/etc/nginx/nginx.conf

volumes:
  elasticsearch-data:
    driver: local
  postgres-data:
    driver: local
  nginx-data:
    driver: local
