version: 2.1
jobs:
  test:
    docker:
      - image: circleci/ruby:2.3.8-node-browsers
        environment:
          RAILS_ENV: test
      - image: mdillon/postgis:9.5
        environment:
          POSTGRES_USER: safecast
          POSTGRES_DB: safecast
          POSTGRES_PASSWORD: ""
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - safecastapi-{{ checksum "Gemfile.lock" }}
            - safecastapi-
      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: safecastapi-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for elasticsearch
          command: dockerize -wait tcp://localhost:9200 -timeout 1m
      - run:
          name: Configure database
          command: cp config/database.yml.ci config/database.yml
      - run:
          name: Install psql client
          command: |
            sudo apt-get update
            sudo apt-get install -y postgresql-client
      - run:
          name: Load schema
          command: |
            psql -h localhost -p 5432 -U safecast safecast -c 'DROP EXTENSION postgis CASCADE'
            bundle exec rake db:schema:load --trace
      - run:
          name: Run rubocop
          command: |
            bundle exec rubocop
      - run:
          name: Run rspec
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results

  deploy_dev:
    docker:
      - image: circleci/ruby:2.3.8-node-browsers
    steps:
      - checkout
      - run:
          name: fake deploy dev
          command: true

  deploy_prd:
    docker:
      - image: circleci/ruby:2.3.8-node-browsers
    steps:
      - checkout
      - run:
          name: fake deploy prd
          command: true

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - hold_dev:
          type: approval
          requires:
            - build
      - deploy_dev:
          requires:
            - hold_dev
      - hold_prd:
          type: approval
          requires:
            - deploy_dev
      - deploy_prd:
          requires:
            - hold_prd
