version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.8
    steps:
      - checkout
      - run: bundle exec rake db:structure:load
      - run: bundle exec rubocop
      - run: bundle exec rspec spec
