development:
  adapter: postgis
  schema_search_path: "public,postgis"
  script_dir: /usr/local/share/postgis
  encoding: unicode
  database: safecast_development
  pool: 5
  username: safecast
  su_username: safecast
  password:

test:
  adapter: postgis
  schema_search_path: "public,postgis"
  script_dir: /usr/local/share/postgis
  encoding: unicode
  database: safecast_test
  pool: 5
  username: safecast
  su_username: safecast
  password:
  min_messages: warning

production:
  adapter: postgis
  schema_search_path: "public,postgis"
  script_dir: /usr/local/share/postgis
  encoding: unicode
  database: safecast
  pool: 5
  username: safecast
  password:
  su_username: safecast
  su_password: <%= ENV['POSTGRESQL_PASSWORD'] %>
